### ISSUE TITLE
can2win Segmentation fault

### ISSUE THREAD

**Issue by AlfredoVDLC** [TDahlmann/canpp#8] opened 2024-07-24 16:43 UTC
Hello!, 
I am able to successfully run can2win in Debian 5.10.120, but unable to do it in Debian 6.1.94 neither Ubuntu 6.8.0, getting "Segmentation Fault" when connecting from windows can++ application. Any clue to solve this? 
6.8
![Segmentation fault](https://github.com/user-attachments/assets/e5aee1bb-f1c3-49cc-b8b6-56b102ff9937)

**Comment by TDahlmann** [comment] 2024-08-01 21:30
Hello Alfredo, thanks for testing. Next week when I am back from vacation I will have a look at this issue.

Thomas

**Comment by TDahlmann** [comment] 2024-08-04 18:09
Hi Alfredo, I could reproduce the fault with Ubuntu 24.04. It was an unallocated string pointer on the stack. It is fixed now.

We used can2win a lot some years ago but never had this issue. I assume this occurred now due to better stack protection in current distros or we just had luck with the stack layout :)

Please could you give it a new try?

Thomas

**Comment by AlfredoVDLC** [comment] 2024-08-05 17:42
Hello!, Checked on Ubuntu 6.8.0 and running flawlessly! Thank you so much Thomas! You created an awesome app.

**Comment by TDahlmann** [comment] 2024-08-07 14:18
Great to hear that the issue is fixed and you like can++ :)

**Closed by TDahlmann** 2024-08-07 14:18 UTC
